[package]
org = "ballerina"
name = "serdes"
version = "0.1.0"
distribution = "2201.2.0"

[[platform.java11.dependency]]
path = "../native/build/libs/serdes-native-0.1.0.jar"
groupId = "io.ballerina.stdlib"
artifactId = "serdes-native"
version = "0.1.0"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-3.21.2.jar"
groupId = "com.google.protobuf"
artifactId = "protobuf-java"
version = "3.21.2"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-util-3.21.2.jar"
groupId = "com.google.protobuf"
artifactId = "protobuf-java-util"
version = "3.21.2"
